// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse grouping for the UI.
 */
export type Category = "system" | "league" | "manager" | "patcher" | "storage" | "library";
