// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single key/value detail row attached to a check.
 */
export type CheckDetail = { key: string; value: string };
