// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Check } from "./Check";

/**
 * Full diagnostic report returned by `run_diagnostics`.
 */
export type DiagnosticReport = {
  /**
   * ISO-8601 UTC timestamp.
   */
  generatedAt: string;
  /**
   * Manager version (matches `Cargo.toml`).
   */
  appVersion: string;
  /**
   * All checks in display order.
   */
  checks: Array<Check>;
};
